### ISSUE TITLE
local host 無法進入 

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#16]
是不是我需要有什麼檔案才能開啟瀏覽？yarn start 啟動後出現這個頁面
![Uploading 螢幕快照 2018-06-07 上午12.08.38.png…]()

**Comment by sexyoung** [comment]
圖片沒有出現？我看不到

**Comment by sexyoung** [comment]
你要不要先下 `yarn` 然後再下 `yarn start` 試試
