### ISSUE TITLE
St Albans 詳情頁面內三個按鈕個別載入三個pdf檔案

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#18]
Financial summary 檔案載點 https://drive.google.com/open?id=11a1xqGLSMBs1TibMgZJtEsbDhNxUKOXz
Plans & Details 檔案載點 https://drive.google.com/open?id=12rlOpkAcTupV2gq5vlfup_zUtLDWwH1Z
中文版簡報 檔案載點 https://drive.google.com/open?id=1brXg3G0DQCvdogilNJIvRLDI66P1AZM1

**Comment by sexyoung** [comment]
done.
