### ISSUE TITLE
SendGrid 服務凍結信件內容

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#22]
信裡提到的密碼、API曝光是因為我們兩邊登入操作的關係嗎？需要照他裡面說的處理或是就直接之後用正式申請的gmail設定就好呢？
信件內容如下：

Your ticket, #1519947 has been updated!

To check the status of the ticket and add additional comments, follow the link here support.sendgrid.com/hc/requests/1519947, or you can also update this ticket by responding directly to this email.

Dear SendGrid Customer,

Your SendGrid account has been temporarily suspended as we have detected that your account's credentials (password and/or API key) are publicly listed on the code repository GitHub. This is a dangerous practice which may result in your account being used by unauthorized third parties to send malicious content and which may incur damage to your reputation as a quality sender and charges against your account for high usage that you did not perform.

Before you ask for your account's reactivation, please ensure that you:
1) Change your account's password: https://sendgrid.com/docs/Classroom/Basics/Account/how_do_i_reset_my_password.html. If your account was created using Heroku or IBM BlueMix, you must use our password reset form.
2) Delete and update exposed API keys in your account: https://sendgrid.com/docs/User_Guide/Settings/api_keys.html#-Inactivate-an-API-Key
3) Enable two-factor authentication for your account
4) Remove your account credentials and API keys from any public listings on code repositories or associated comments on sites such as GitHub or BitBucket.

Please see the following link(s) for locations where your credentials have been found to be publicly exposed:

https://github.com/katiechoupapa/katiechoupapa.github.io/blob/fc04ec035c1330c14cae0101a04bce3997b211ff/src/HomePage/blocks/Contact/index.js

Please respond directly to this ticket in order to start the reactivation process and be aware that an account in a suspended state at the end of the month will still incur subscription auto-renewal billing. Sending wanted mail is paramount to SendGrid, therefore we would like to work with you to identify the cause of and resolve this unwanted activity. We apologize for any inconvenience this may have caused and truly appreciate your continued business. Thank you for using SendGrid.

**Comment by sexyoung** [comment]
嗯 這邊的確是我們的 api key 曝光了，我來把key清掉再試試看

**Comment by sexyoung** [comment]
改用 mailjet 已串接完畢，再提供 public key 跟 secret key 到 messenger 給我

**Comment by sexyoung** [comment]
已使用 mailjet 處理
