### ISSUE TITLE
push master 失敗

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#23]
又失敗...到底哪裡做錯了呢？
![2018-06-20 2 48 06](https://user-images.githubusercontent.com/39607944/41611856-807948bc-7434-11e8-8d74-dfd4139fc573.png)

**Comment by sexyoung** [comment]
先 pull 再 push

**Comment by katiechoupapa** [comment]
要在master線還是本機pull？
