### ISSUE TITLE
Services 三塊順序更換＆項目標題＆內容

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#26]
- 目前的Immigration Assistance跟Property Development調換位置

左邊
標題：Joint Ventures
滑入顯示內容：
Scheracon can work together with investors, we work together with investors as stakeholder to
develop business opportunity.

中間
標題：Property Development
滑入顯示內容：
We source suitable property for development with profitable and value shareholder returns.

右邊
標題：Consultants 
滑入顯示內容：
We provide the service to prospective investors for the best forms of entry into the potential
opportunity that is more appropriate to their positive.

**Comment by sexyoung** [comment]
done.
