### ISSUE TITLE
PROPOSED DEVELOPMENT 新增一個 Hawthorn East (首頁link&page)

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#28]
首頁PROPOSED DEVELOPMENT區塊
圖片載點 https://drive.google.com/open?id=1DVCz3fsdWljWl03USk-gICkM2dMJEg8T
圓圈內文字： 
Hawthorn East (大字) 
Victoria（小字）

Page 內容：
首頁 slider文字：
HAWTHORN EAST (大字) 
BOUTIQUE PERMIT APPROVED（小字）
圖片按編號順序 https://drive.google.com/open?id=1Aqtqsvd_rvpMVx2udRrhN5ErB5E8YoDX

**Comment by sexyoung** [comment]
啊 Hawthorn East 下面也是三欄式而且也有三個按鈕是嗎？也一樣有彈跳視窗?

**Comment by sexyoung** [comment]
done.
