### ISSUE TITLE
yarn start 失敗，更改Director頁面上傳失敗

### ISSUE THREAD

**Issue by katiechoupapa** [katiechoupapa/katiechoupapa.github.io#3]
我先把程式（終端、fork、atom）都打開了，然後再Atom裡編輯了Director 標題錯字，也stage+commit了，但在yarn build 顯示erro...
![2018-06-02 8 32 55](https://user-images.githubusercontent.com/39607944/40873497-5913dd20-66a4-11e8-81e5-f68ca450154c.png)

**Comment by sexyoung** [comment]
重新 yarn 即可
